//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liuk_Music_CS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class secrets : global::System.Configuration.ApplicationSettingsBase {
        
        private static secrets defaultInstance = ((secrets)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new secrets())));
        
        public static secrets Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!")]
        public char prefix {
            get {
                return ((char)(this["prefix"]));
            }
            set {
                this["prefix"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ODkwMzE2NjM5ODIyODM1NzEy.YUuB_A.annYdpKkSiDh5ufOG24vAj7kdds")]
        public string token {
            get {
                return ((string)(this["token"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3dXMSntitJ1NO_xVis-trtsziX_qx9XDykAO2rS0p9ODYPaO3WhenUdIZ9eBuL-P")]
        public string lyrics {
            get {
                return ((string)(this["lyrics"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Liuk music!")]
        public string bot_name {
            get {
                return ((string)(this["bot_name"]));
            }
            set {
                this["bot_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float volume {
            get {
                return ((float)(this["volume"]));
            }
            set {
                this["volume"] = value;
            }
        }
    }
}
